### Step 1. 필요한 라이브러리 임포트

In [2]:
import pandas as pd

### Step 2. [데이터](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) 확인

- order_id 주문번호
- quantity 주문 개수
- item_name 주문한 상품명
- choice_description 선택사항
- item_price 가격

### Step 3. 데이터 불러오기


**read_csv를 통해 데이터를 올바른 형태로 불러온 뒤 chipo에 저장해주세요**  
data: chipotle.tsv

In [14]:
chipo = pd.read_csv('../da_data/chipotle.tsv', sep='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [15]:
chipo.loc[1, 'choice_description']

'[Clementine]'

In [21]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

### Step 4. 누락값 확인하기
chipo에서 누락값이 존재하는지 확인해주세요

In [33]:
# 누락값 전부 찾기
chipo.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

### Step 5. item_price에서 $를 없애고 float 형식으로 새롭게 저장해주세요.

In [32]:
def normalize_price(x):
    return float(x[1:])

chipo['item_price'] = chipo['item_price'].apply(normalize_price)

TypeError: 'float' object is not subscriptable

### Step 6. 아이템별 주문 수를 출력해주세요

In [36]:
chipo.groupby('item_name')['order_id'].size()

item_name
6 Pack Soft Drink                         54
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            162
Bowl                                       2
Burrito                                    6
Canned Soda                              104
Canned Soft Drink                        301
Carnitas Bowl                             68
Carnitas Burrito                          59
Carnitas Crispy Tacos                      7
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             726
Chicken Burrito                          553
Chicken Crispy Tacos                      47
Chicken Salad                              9
Chicken Salad Bowl                       110
Chicken Soft Tacos                       115
Chips                                    211
Chips and Fresh Tomato Salsa             110
Chips and Guacamole                      479
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        22
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     43
Chips and Tomatillo Red Chili Salsa       48
Chips and Tomatillo-Green Chili Salsa     31
Chips and Tomatillo-Red Chili Salsa       20
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          27
Salad                                      2
Side of Chips                            101
Steak Bowl                               211
Steak Burrito                            368
Steak Crispy Tacos                        35
Steak Salad                                4
Steak Salad Bowl                          29
Steak Soft Tacos                          55
Veggie Bowl                               85
Veggie Burrito                            95
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          7
Name: order_id, dtype: int64

### Step 7. 아이템별 주문 총량을 출력해주세요.

In [37]:
chipo.groupby('item_name')['quantity'].sum()

item_name
6 Pack Soft Drink                         55
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            211
Bowl                                       4
Burrito                                    6
Canned Soda                              126
Canned Soft Drink                        351
Carnitas Bowl                             71
Carnitas Burrito                          60
Carnitas Crispy Tacos                      8
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             761
Chicken Burrito                          591
Chicken Crispy Tacos                      50
Chicken Salad                              9
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Chips                                    230
Chips and Fresh Tomato Salsa             130
Chips and Guacamole                      506
Chips and Mild Fresh Tomato Salsa          1
Chips and Roasted Chili Corn Salsa        23
Chips and Roasted Chili-Corn Salsa        18
Chips and Tomatillo Green Chili Salsa     45
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo-Green Chili Salsa     33
Chips and Tomatillo-Red Chili Salsa       25
Crispy Tacos                               2
Izze                                      20
Nantucket Nectar                          29
Salad                                      2
Side of Chips                            110
Steak Bowl                               221
Steak Burrito                            386
Steak Crispy Tacos                        36
Steak Salad                                4
Steak Salad Bowl                          31
Steak Soft Tacos                          56
Veggie Bowl                               87
Veggie Burrito                            97
Veggie Crispy Tacos                        1
Veggie Salad                               6
Veggie Salad Bowl                         18
Veggie Soft Tacos                          8
Name: quantity, dtype: int64

### Step 8. 각 아이템의 가격을 구해서 unit_price 컬럼에 추가해주세요.
주문당 quantity가 1일때의 가격 (item_price / quantity)

In [ ]:
chipo['unit_price'] = chipo['item_price'] / chipo['quantity']

### Step 9. 아이템별 개당 가격의 평균을 구하고 가장 비싼순으로 5개를 출력해주세요

In [44]:
chipo.groupby('item_name')['unit_price'].mean().sort_values(ascending=False).head()

item_name
Carnitas Salad Bowl    11.056667
Steak Salad Bowl       11.027931
Barbacoa Salad Bowl    10.640000
Carnitas Bowl          10.315588
Steak Bowl             10.232559
Name: unit_price, dtype: float64

### Step 10. 한 주문(같은 order_id)에 20달러 이상 지불한 손님을 출력해주세요.

In [50]:
chipo_price = chipo.groupby('order_id')['item_price'].sum()

In [51]:
chipo_price[chipo_price >= 20]

order_id
4       21.00
18      24.90
20      36.20
21      23.36
26      20.50
        ...
1827    32.95
1829    24.25
1830    23.00
1833    23.50
1834    28.75
Name: item_price, Length: 589, dtype: float64

### Step 11. 위 10번에서 주문량이 2개인 아이템중 가장 많이 팔린 아이템은 무엇인가요?
Chips and Guacamole

In [55]:
# 총 주문 금액이 20달러 이상인 주문 번호
chipo_price_index = chipo_price[chipo_price>=20].index

# 주문 번호가 총 주문 금액이 20달러 이상인 주문 번호에 포함되어 있는가 (True, False값 리턴)
chipo['order_id'].isin(chipo_price_index)

# 포함되어 있는 것만(True인 값만) 리턴
chipo[chipo['order_id'].isin(chipo_price_index)]

,order_id,quantity,item_name,choice_description,item_price,unit_price
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",8.75,8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75,8.75
37,18,1,Chips and Guacamole,NaN,4.45,4.45
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [ ]:
chipo2 = 
chipo2[chipo2['quantity'] == 2]['item_name'].value_counts()

### Step 12. Veggie Salad Bowl은 몇 건 주문되었나요?

In [57]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]

18

### Step 13. Chicken이 포함된 음식은 몇 가지가 있나요?

In [63]:
import re

def check_chicken(x):
    return bool(re.search('Chicken', x))

chipo[chipo['item_name'].apply(check_chicken)]['item_name'].unique()

<StringArray>
[        'Chicken Bowl', 'Chicken Crispy Tacos',   'Chicken Soft Tacos',
      'Chicken Burrito',   'Chicken Salad Bowl',        'Chicken Salad']
Length: 6, dtype: str

In [66]:
chipo[chipo['item_name'].str.contains('Chicken')]['item_name'].unique()

<StringArray>
[        'Chicken Bowl', 'Chicken Crispy Tacos',   'Chicken Soft Tacos',
      'Chicken Burrito',   'Chicken Salad Bowl',        'Chicken Salad']
Length: 6, dtype: str